---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-2-eus-06-08-26"
    bootloader: efi
    cores: 1
    memory: "4G"
    image_size: "40G"
    register_satellite: false
    # packages:
    # - nfs-utils
    # - rpcbind
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
